### ISSUE TITLE
JodelXposed FC when trying to share from gallery

### ISSUE THREAD

**Issue by MrYawnie** [krokofant/JodelXposed#60]
As the title implies, the module FC when trying to share from gallery on latest Jodel update. Log below in screenshot. 

![screenshot_20170221-000545](https://cloud.githubusercontent.com/assets/14262612/23143367/c4bacdcc-f7c9-11e6-8136-72692fc350df.png)

**Comment by Unbrick** [comment]
Could you provide a full stacktrace? The message of the RuntimeException would be interesting.

And which Jodel and which JX version are you on?

**Comment by MrYawnie** [comment]
I'm on latest Jodel 4.34.2 and I build the JX from sources couple days ago. I had to comment out the RemoveBlurFromImages part from Hooks.kt in order for the app to build.. 

```
02-21 16:08:47.011 D/SystemServicesProxy(22587): exclude com.jodelXposed
02-21 16:08:49.871 I/ActivityManager(1985): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.tellm.android.app/com.jodelapp.jodelandroidv3.view.Launcher (has extras)} from uid 10088 pid 8518 on display 0
02-21 16:08:51.053 D/SystemServicesProxy(22587): exclude com.jodelXposed
02-21 16:08:51.357 I/ActivityManager(1985): START u0 {act=android.intent.action.MAIN flg=0x10000000 cmp=com.jodelXposed/.utils.Picker (has extras)} from uid 10225 pid 3694 on display 0
02-21 16:08:51.464 I/ActivityManager(1985): Start proc 2249:com.jodelXposed/u0a213 for activity com.jodelXposed/.utils.Picker
02-21 16:08:51.512 W/System  (2249): ClassLoader referenced unknown path: /data/app/com.jodelXposed-2/lib/arm64
02-21 16:08:52.679 D/SystemServicesProxy(22587): exclude com.jodelXposed
02-21 16:08:54.048 D/JodelXposed(2249): SelectedImage:content://media/external/images/media/51635
02-21 16:08:54.053 W/System.err(2249): 	at com.jodelXposed.utils.Picker.onActivityResult(Picker.kt:163)
02-21 16:08:54.055 W/System.err(2249): 	at com.jodelXposed.utils.Picker.onActivityResult(Picker.kt:163)
02-21 16:08:54.057 E/AndroidRuntime(2249): Process: com.jodelXposed, PID: 2249
02-21 16:08:54.057 E/AndroidRuntime(2249): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=202, result=-1, data=Intent { dat=content://media/external/images/media/51635 flg=0x1 }} to activity {com.jodelXposed/com.jodelXposed.utils.Picker}: java.lang.IllegalArgumentException: width and height must be > 0
02-21 16:08:54.057 E/AndroidRuntime(2249): 	at com.jodelXposed.utils.Picker.onActivityResult(Picker.kt:163)
02-21 16:08:54.095 W/ActivityManager(1985):   Force finishing activity com.jodelXposed/.utils.Picker
02-21 16:08:54.151 W/ActivityManager(1985):  Dismiss app error dialog : com.jodelXposed
02-21 16:08:54.177 I/ActivityManager(1985): Process com.jodelXposed (pid 2249) has died
02-21 16:08:55.081 D/SystemServicesProxy(22587): exclude com.jodelXposed
02-21 16:08:56.670 D/SystemServicesProxy(22587): exclude com.jodelXposed
02-21 16:08:57.819 D/SystemServicesProxy(22587): exclude com.jodelXposed
02-21 16:08:58.989 D/SystemServicesProxy(22587): exclude com.jodelXposed

```

**Comment by krokofant** [comment]
What app do you use for picking?

**Comment by MrYawnie** [comment]
Snap camera + gallery https://play.google.com/store/apps/details?id=com.marginz.snap

**Comment by MrYawnie** [comment]
Tried with other galleries as well, same issue. I never get FC notice, nor does Jodel crash. Just nothing happens after  I choose image from gallery. JX crashes in background without pop-up, with the log I posted above (user MatLog to get it).

**Comment by Unbrick** [comment]
Fixed and pushed, tested with Snap Camera + Gallery and for me it works now, try it yourself

**Comment by MrYawnie** [comment]
Awesome, works now! Thanks :)
